/* Generated By:JavaCC: Do not edit this line. GepardParserConstants.java */
package fdbs.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.fdbs.parser.OtherFilesGen#start()
 */
public interface GepardParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int CREATE = 1;
    /**
     * RegularExpression Id.
     */
    int TABLE = 2;
    /**
     * RegularExpression Id.
     */
    int INTEGER = 3;
    /**
     * RegularExpression Id.
     */
    int VARCHAR = 4;
    /**
     * RegularExpression Id.
     */
    int CONSTRAINT = 5;
    /**
     * RegularExpression Id.
     */
    int CHECK = 6;
    /**
     * RegularExpression Id.
     */
    int PRIMARYKEY = 7;
    /**
     * RegularExpression Id.
     */
    int UNIQUE = 8;
    /**
     * RegularExpression Id.
     */
    int HORIZONTAL = 9;
    /**
     * RegularExpression Id.
     */
    int IS = 10;
    /**
     * RegularExpression Id.
     */
    int NOT = 11;
    /**
     * RegularExpression Id.
     */
    int IN = 12;
    /**
     * RegularExpression Id.
     */
    int FOREIGNKEY = 13;
    /**
     * RegularExpression Id.
     */
    int REFERENCES = 14;
    /**
     * RegularExpression Id.
     */
    int BETWEEN = 15;
    /**
     * RegularExpression Id.
     */
    int DROP = 16;
    /**
     * RegularExpression Id.
     */
    int CASCADE = 17;
    /**
     * RegularExpression Id.
     */
    int CONSTRAINTS = 18;
    /**
     * RegularExpression Id.
     */
    int DELETE = 19;
    /**
     * RegularExpression Id.
     */
    int UPDATE = 20;
    /**
     * RegularExpression Id.
     */
    int SET = 21;
    /**
     * RegularExpression Id.
     */
    int INSERT = 22;
    /**
     * RegularExpression Id.
     */
    int INTO = 23;
    /**
     * RegularExpression Id.
     */
    int VALUES = 24;
    /**
     * RegularExpression Id.
     */
    int SELECT = 25;
    /**
     * RegularExpression Id.
     */
    int WHERE = 26;
    /**
     * RegularExpression Id.
     */
    int AND = 27;
    /**
     * RegularExpression Id.
     */
    int OR = 28;
    /**
     * RegularExpression Id.
     */
    int COUNT = 29;
    /**
     * RegularExpression Id.
     */
    int SUM = 30;
    /**
     * RegularExpression Id.
     */
    int GROUPBY = 31;
    /**
     * RegularExpression Id.
     */
    int HAVING = 32;
    /**
     * RegularExpression Id.
     */
    int FROM = 33;
    /**
     * RegularExpression Id.
     */
    int DIGIT = 34;
    /**
     * RegularExpression Id.
     */
    int LETTER = 35;
    /**
     * RegularExpression Id.
     */
    int LPAREN = 36;
    /**
     * RegularExpression Id.
     */
    int RPAREN = 37;
    /**
     * RegularExpression Id.
     */
    int UNDERSCORE = 38;
    /**
     * RegularExpression Id.
     */
    int COMMA = 39;
    /**
     * RegularExpression Id.
     */
    int SEMICOLON = 40;
    /**
     * RegularExpression Id.
     */
    int SINGLEQUOTE = 41;
    /**
     * RegularExpression Id.
     */
    int OPERATOR = 42;
    /**
     * RegularExpression Id.
     */
    int MINUS = 43;
    /**
     * RegularExpression Id.
     */
    int NULL = 44;
    /**
     * RegularExpression Id.
     */
    int DOT = 45;
    /**
     * RegularExpression Id.
     */
    int AST = 46;
    /**
     * RegularExpression Id.
     */
    int FSLASH = 47;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\"CREATE \"",
            "\"TABLE \"",
            "\"INTEGER\"",
            "\"VARCHAR\"",
            "\"CONSTRAINT \"",
            "\"CHECK \"",
            "<PRIMARYKEY>",
            "<UNIQUE>",
            "<HORIZONTAL>",
            "\" IS \"",
            "\"NOT \"",
            "\"IN \"",
            "\"FOREIGN KEY \"",
            "\"REFERENCES \"",
            "\"BETWEEN \"",
            "\"DROP \"",
            "\"CASCADE \"",
            "\"CONSTRAINTS\"",
            "\"DELETE \"",
            "\"UPDATE \"",
            "\"SET \"",
            "\"INSERT \"",
            "\"INTO \"",
            "<VALUES>",
            "\"SELECT \"",
            "\"WHERE \"",
            "\" AND \"",
            "\" OR \"",
            "<COUNT>",
            "<SUM>",
            "<GROUPBY>",
            "\" HAVING \"",
            "\"FROM \"",
            "<DIGIT>",
            "<LETTER>",
            "<LPAREN>",
            "<RPAREN>",
            "\"_\"",
            "<COMMA>",
            "\";\"",
            "\"\\\'\"",
            "<OPERATOR>",
            "\"-\"",
            "\"NULL\"",
            "\".\"",
            "\"*\"",
            "\"/\"",
            "\" \"",
            "\"\\u00c3\\u201e\"",
            "\"\\u00c3\\u0153\"",
            "\"\\u00c3\\u2013\"",
            "\"\\u00c3\\u00a4\"",
            "\"\\u00c3\\u00bc\"",
            "\"\\u00c3\\u00b6\"",
            "\"\\u00c3\\u0178\"",
    };

}
